export const styles = {
    container: {
        background: 'white',
        width: '100vw',
        height: '100vh',
        display: 'flex',
        flexDirection: "column"
      },
    nextBtn:{
        marginTop:"35px",
        
        width: "200px",
        height: "65px",
        flexShrink: '0',
        display: "flex",
        justifyContent: "center",
        flexShrink: "0",
        color: "#FFF",
        textAlign: "center",
        alignItems: 'center',
        fontFamily: "Inter",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal",
        cursor:"pointer",
        background: "#337FED",
        filter: "drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))",
        border:"none",
        borderRadius:"30px"
      },
      nextBtn2:{
        marginTop:"30px",
        marginBottom:"30px",
        marginLeft:"56%",
        width: "200px",
        height: "65px",
        flexShrink: '0',
        display: "flex",
        justifyContent: "center",
        flexShrink: "0",
        color: "#FFF",
        textAlign: "center",
        alignItems: 'center',
        fontFamily: "Inter",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal",
        cursor:"pointer",
        background: "#337FED",
        filter: "drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))",
        border:"none",
        borderRadius:"30px"
      },
      nextBtn3:{
        marginTop:"50px",
        marginBottom:"50px",
        marginLeft:"43%",
        width: "200px",
        height: "65px",
        flexShrink: '0',
        display: "flex",
        justifyContent: "center",
        flexShrink: "0",
        color: "#FFF",
        textAlign: "center",
        alignItems: 'center',
        fontFamily: "Inter",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal",
        cursor:"pointer",
        background: "#337FED",
        filter: "drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))",
        border:"none",
        borderRadius:"30px"
      },
      subtitle:{
        marginTop:"30px",
        display: "flex",
        marginLeft:"94px",
        flexShrink: "0",
        color: "#000",
        fontFamily: "Inter",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "normal",
        marginBottom:"50px"
      },
      title:{
        display: "flex",
        marginLeft:"94px",
        flexShrink: "0",
        color: "#000",
        fontFamily: "Inter",
        fontSize: "55px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal"
      },
      title2:{
        display: "flex",
        marginLeft:"94px",
        flexShrink: "0",
        color: "#000",
        marginTop:"-40px",
        fontFamily: "Inter",
        fontSize: "55px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal",
        marginBottom:"50px"
      },
      th:{
        cursor: "pointer",
        margin: '0 33px',
        marginBottom:"100px"
      },
      detailBox:{
        display: "flex",
        justifyContent: "center",
        alignItems: 'center',
      }
}