export const styles = {
    container: {
      background: 'white',
      width: '100vw',
      height: '100vh',
      display: 'flex',
      flexDirection: "column"
    },
    nextBtn:{
        marginTop:"35px",
        marginLeft:"40%",
        width: "320px",
        height: "80px",
        flexShrink: '0',
        display: "flex",
        justifyContent: "center",
        flexShrink: "0",
        color: "#FFF",
        textAlign: "center",
        alignItems: 'center',
        fontFamily: "Inter",
        fontSize: "30px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal",
        cursor:"pointer",
        background: "#F3887A",
        filter: "drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))",
        border:"none",
        borderRadius:"30px"
      },
      title:{
        marginTop: '0px',
        display: "flex",
        marginLeft:"94px",
        width: "783px",
        flexShrink: "0",
        color: "#000",
        fontFamily: "Inter",
        fontSize: "55px",
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: "normal"
      },
}